version: 0.2
os: linux

phases:
  build:
    commands:
      - echo Build started on `date`
      - mvn test
  post_build:
    commands:
      - echo Build completed on `date`
      - mvn package
artifacts:
  files:
    - target/springboot-jersey-swagger-1.0.0.jar
    - appspec.yml
        
  
    
