# use a random unassigned HTTP port by scanning for free port
server:
  port: ${PORT:8080}


# For Spring Actuator /info endpoint
info:
    artifact: springboot-jesrsey-swagger
    name: springboot-jesrsey-swagger
    description: Spring Jersey Swagger Example
    version: 1.0.0

datasource:
  validationQuery: SELECT 1
  initialSize: 1
  maxActive: 3
  testWhileIdle: true
  testOnBorrow: true

jpa:
  show-sql: true
  #database: postgresql
  format_sql: true
  properties:
    #hibernate:
      #dialect: org.hibernate.dialect.PostgreSQLDialect
      #ddl-auto: update
    org:
      hibernate:
        flushMode: AUTO

#logging:
#  level:
#    org.springframework: DEBUG

spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://crxxphw9xlft.us-west-1.rds.amazonaws.com:5432/rapiddatabase
    username: rapiduser
    password: rapidpassword
    
  jersey:
    type: filter
    